### ISSUE TITLE
Import HeapedVector, not HeapedVectors

### ISSUE THREAD

**Issue by dpsanders** [yashcodes/CharibdeOptim.jl#11]
`HeapedVector` is what `IntervalOptimisation` exports.

**Comment by yashcodes** [comment]
I tried it, but then`filter_elements!` get became not defined variable.
```
julia> ibc_minimise( X -> ( (x,y) = X; x^2 + y^2 ) , IntervalBox(2..3, 3..4))
ERROR: UndefVarError: filter_elements! not defined
Stacktrace:
 [1] #ibc_minimise#1(::Type, ::Float64, ::Function, ::getfield(Main, Symbol("##9#10")), ::IntervalBox{2,Float64}) at /Users/yash/code/CharibdeOptim/src/IBC.jl:29
 [2] ibc_minimise(::Function, ::IntervalBox{2,Float64}) at /Users/yash/code/CharibdeOptim/src/IBC.jl:4
 [3] top-level scope at none:0
```

**Comment by dpsanders** [comment]
Because it is not exported.

**Comment by yashcodes** [comment]
Thatswhy I need to import `StrartegyBase.jl` and `Sortedvectors.jl`or `HeapedVectors.jl` modules.

**Comment by dpsanders** [comment]
I think you just need to export filter_elements! from IntervalOptimisation.jl

**Comment by dpsanders** [comment]
Well if you need to import them, just import them. Basically the problem is that you are using interbal functions from another package, instead of just using the public exported interface from that package.

**Comment by yashcodes** [comment]
But filter_elements! is not exported by IntervalOptimisation.jl moudule, it is exported by StrategyBase.jl module, thats why Imported StrategyBase.jl

**Comment by yashcodes** [comment]
I think we should just export filter_elements! from StrategyBase.jl

**Comment by dpsanders** [comment]
You have to export it from IntervalOptimisation.jl

**Comment by yashcodes** [comment]
OK.

**Comment by yashcodes** [comment]
Now when I exported `SortedVector` and `filter_elemets!` from IO.jl it still giving the same error that
`ERROR: LoadError: UndefVarError: HeapedVector not defined` in travis.ci while, everything is working just fine in my local machine .

**Comment by yashcodes** [comment]
please see the last commit I made in PR [10](https://github.com/yashcodes/CharibdeOptim.jl/pull/10)
